### ISSUE TITLE
the algorithm

### ISSUE THREAD

**Issue by hhenjoy** [sambuddhac/OPF#3]
Dear professor,
     Sorry to bother you again, I wonder if this algorithm can be extended to multiple periods. And also in that case, do I need to pick a set for rho (the penalty parameter), for example, rho1 for period 1, rho 2 for period 2. etc.
     Thank you for your time and consideration.

**Comment by sambuddhac** [comment]
Dear @hhenjoy 

No bothering at all. Please check my repository https://github.com/sambuddhac/LASCOPF_Load_Variation and the published journal paper, https://www.sciencedirect.com/science/article/abs/pii/S0142061519309524 for th multiple period (N-1) SCOPF version. You can vary the rho for better convergence. I am in the process of translating all these codes from C++ to Julia and releasing as a more comprehensive package. Any help in the form of PR and/or issues is most welcome !!!

**Comment by hhenjoy** [comment]
Dear professor,
Thank you so much for your nice reply.  I wonder if you encountered a numerical problem when using the solver GUROBI as I see the last value of Rho (the penalty factor) in your output file is very large. And if you also have came across a numerical problem, how did you solve it.
I would be grateful if you have some clues.
Thank you very much for your time and attention.
Best regards.

**Comment by sambuddhac** [comment]
Dear @hhenjoy , you are right !!!! ADMM based PMP algorithm indeed tends to be a bit unstable and requires thousands of iterations to converge. The tuning of Rho is an extremely notorious, nefarious, and challenging task and is infamous within the optimization community. However, the ease of computation within each iteration and therefore the relative speed as compared to other distributed algorithms far outweigh this shortcoming. Nevertheless, in our paper on the LASCOPF that I pointed to, previously, one way we addressed this is wrapping the ADMM layer inside an outer APP layer. Please take a look at it and let me know if you have any questions.
